/-
Brownian scaling for arbitrary finite-generation cylinders.

The first-level scaling identity in `Minkowski.TubeRenewal` is iterated here without
introducing a new stochastic argument.  A generation word has a product time ratio,
the corresponding sum of half-logarithmic renewal delays, and the natural product
weight.  Its Brownian image therefore has the law of the full Brownian image at the
delayed scale, multiplied by that weight after tube normalization.
-/
import BrownianImages.Minkowski.Generation
import BrownianImages.Minkowski.TubeRenewal

namespace BrownianImages

open MeasureTheory ProbabilityTheory Set TopologicalSpace
open scoped ENNReal NNReal Topology

noncomputable section

namespace System

variable {iota : Type*} [Fintype iota] [Nonempty iota] (S : System iota)

/-- The left endpoint of the affine similarity represented by a generation word. -/
def generationShift (k : ℕ) (w : GenerationWord iota k) : ℝ :=
  S.generationMap k w 0

/-- The sum of the half-logarithmic renewal delays along a generation word. -/
def generationHalfLogRatio (S : System iota) :
    (k : ℕ) → GenerationWord iota k → ℝ
  | 0, _ => 0
  | Nat.succ k, w =>
      S.generationHalfLogRatio k w.1 + S.halfLogRatio w.2

omit [Nonempty iota] in
/-- The empty word has half-logarithmic ratio zero. -/
@[simp]
theorem generationHalfLogRatio_zero (w : GenerationWord iota 0) :
    S.generationHalfLogRatio 0 w = 0 := rfl

omit [Nonempty iota] in
/-- Appending a letter adds its half-logarithmic ratio `β_i`. -/
@[simp]
theorem generationHalfLogRatio_succ (k : ℕ)
    (w : GenerationWord iota (Nat.succ k)) :
    S.generationHalfLogRatio (Nat.succ k) w =
      S.generationHalfLogRatio k w.1 + S.halfLogRatio w.2 := rfl

omit [Nonempty iota] in
/-- Every finite-word delay belongs to the additive subgroup generated by the
one-letter renewal delays. -/
theorem generationHalfLogRatio_mem_closure :
    ∀ (k : ℕ) (w : GenerationWord iota k),
      S.generationHalfLogRatio k w ∈
        AddSubgroup.closure (Set.range S.halfLogRatio)
  | 0, _ => by
      simp [generationHalfLogRatio]
  | Nat.succ k, w => by
      rw [generationHalfLogRatio_succ]
      exact AddSubgroup.add_mem _
        (generationHalfLogRatio_mem_closure k w.1)
        (AddSubgroup.subset_closure (Set.mem_range_self w.2))

omit [Nonempty iota] in
/-- Every finite-word similarity maps the unit interval into itself. -/
theorem mapsTo_generationMap_unitInterval :
    ∀ (k : ℕ) (w : GenerationWord iota k),
      MapsTo (S.generationMap k w) (Set.Icc (0 : ℝ) 1) (Set.Icc 0 1)
  | 0, _ => by
      simpa [generationMap] using Set.mapsTo_id (Set.Icc (0 : ℝ) 1)
  | Nat.succ k, w => by
      have houter : MapsTo (S.map w.2) (Set.Icc (0 : ℝ) 1) (Set.Icc 0 1) := by
        change MapsTo (fun x => S.ratio w.2 * x + S.shift w.2)
          (Set.Icc (0 : ℝ) 1) (Set.Icc 0 1)
        exact S.mapsTo w.2
      exact houter.comp (mapsTo_generationMap_unitInterval k w.1)

omit [Nonempty iota] in
/-- The left endpoint of a finite-word similarity is nonnegative. -/
theorem generationShift_nonneg (k : ℕ) (w : GenerationWord iota k) :
    0 ≤ S.generationShift k w := by
  exact (S.mapsTo_generationMap_unitInterval k w
    (show (0 : ℝ) ∈ Set.Icc 0 1 by norm_num)).1

omit [Nonempty iota] in
/-- A generation cylinder is literally the affine copy with the product ratio. -/
theorem IsAttractor.generationCylinder_eq_affineTimeCompact
    {K : Set ℝ} (hK : S.IsAttractor K)
    (k : ℕ) (w : GenerationWord iota k) :
    hK.generationCylinder S k w =
      affineTimeCompact (S.generationShift k w).toNNReal
        (S.generationRatio k w).toNNReal hK.toNonemptyCompacts := by
  apply NonemptyCompacts.ext
  rw [hK.coe_generationCylinder S k w, coe_affineTimeCompact]
  apply Set.image_congr
  intro t _ht
  rw [Real.coe_toNNReal _ (S.generationShift_nonneg k w),
    Real.coe_toNNReal _ (S.generationRatio_pos k w).le]
  have hsub := S.generationMap_sub k w t 0
  unfold generationShift
  simp only [sub_zero] at hsub
  linarith

omit [Nonempty iota] in
/-- The physical radius at the delayed generation scale is divided by the square
root of the product time ratio. -/
theorem tubeRadiusReal_sub_generationHalfLogRatio :
    ∀ (k : ℕ) (w : GenerationWord iota k) (v : ℝ),
      tubeRadiusReal (v - S.generationHalfLogRatio k w) =
        tubeRadiusReal v / Real.sqrt (S.generationRatio k w)
  | 0, w, v => by
      simp [generationHalfLogRatio, generationRatio]
  | Nat.succ k, w, v => by
      have hprev := tubeRadiusReal_sub_generationHalfLogRatio k w.1 v
      have hletter := tubeRadiusReal_sub_halfLogRatio S
        (v - S.generationHalfLogRatio k w.1) w.2
      rw [generationHalfLogRatio_succ]
      rw [show v - (S.generationHalfLogRatio k w.1 + S.halfLogRatio w.2) =
        (v - S.generationHalfLogRatio k w.1) - S.halfLogRatio w.2 by ring]
      rw [hletter, hprev, generationRatio]
      rw [Real.sqrt_mul (S.generationRatio_pos k w.1).le]
      field_simp

omit [Nonempty iota] in
/-- The planar Brownian Jacobian and profile normalization combine to the natural
product weight of a generation cylinder. -/
theorem exp_tubeExponent_mul_generationRatio (s : ℝ) :
    ∀ (k : ℕ) (w : GenerationWord iota k) (v : ℝ),
      Real.exp (tubeExponent s * v) * S.generationRatio k w =
        S.generationWeight s k w *
          Real.exp (tubeExponent s *
            (v - S.generationHalfLogRatio k w))
  | 0, w, v => by
      simp [generationRatio, generationWeight, generationHalfLogRatio]
  | Nat.succ k, w, v => by
      rw [generationRatio, generationWeight, generationHalfLogRatio_succ]
      calc
        Real.exp (tubeExponent s * v) *
            (S.generationRatio k w.1 * S.ratio w.2) =
            (Real.exp (tubeExponent s * v) *
              S.generationRatio k w.1) * S.ratio w.2 := by ring
        _ = (S.generationWeight s k w.1 *
              Real.exp (tubeExponent s *
                (v - S.generationHalfLogRatio k w.1))) * S.ratio w.2 := by
          rw [exp_tubeExponent_mul_generationRatio s k w.1 v]
        _ = S.generationWeight s k w.1 *
            (Real.exp (tubeExponent s *
                (v - S.generationHalfLogRatio k w.1)) * S.ratio w.2) := by
          ring
        _ = S.generationWeight s k w.1 *
            (S.tubeWeight s w.2 *
              Real.exp (tubeExponent s *
                ((v - S.generationHalfLogRatio k w.1) -
                  S.halfLogRatio w.2))) := by
          rw [exp_tubeExponent_mul_ratio S s
            (v - S.generationHalfLogRatio k w.1) w.2]
        _ = (S.generationWeight s k w.1 * S.tubeWeight s w.2) *
            Real.exp (tubeExponent s *
              (v - (S.generationHalfLogRatio k w.1 +
                S.halfLogRatio w.2))) := by
          ring_nf

end System

section Brownian

variable {iota : Type*} [Fintype iota] [Nonempty iota] (S : System iota)
variable {Omega : Type*} [MeasurableSpace Omega]
variable {P : Measure Omega} {W : ℝ≥0 → Omega → Plane}

omit [Nonempty iota] in
/-- Exact tube-mass law for an arbitrary finite-generation Brownian cylinder. -/
theorem IsPlanarBrownian.map_tubeMass_brownianGenerationCylinder_eq
    [IsProbabilityMeasure P] (hW : IsPlanarBrownian W P)
    {K : Set ℝ} {s : ℝ} {mu : Measure ℝ}
    (hmu : S.IsNatural K s mu) (k : ℕ)
    (w : GenerationWord iota k) (v : ℝ) :
    P.map (fun omega => tubeMass (tubeRadiusReal v)
        (hmu.attractor.brownianGenerationCylinder S W omega k w)) =
      P.map (fun omega => S.generationRatio k w *
        tubeMass (tubeRadiusReal
          (v - S.generationHalfLogRatio k w))
          (brownianImage W hmu.compactAttractor omega)) := by
  have hrne : (S.generationRatio k w).toNNReal ≠ 0 :=
    ne_of_gt (Real.toNNReal_pos.mpr (S.generationRatio_pos k w))
  have hlaw := hW.map_tubeMass_affineBrownianCompactPiece_eq
    (tubeRadiusReal_pos v) (S.generationShift k w).toNNReal hrne
      hmu.compactAttractor hmu.attractor.2.2.1
  simpa only [System.IsAttractor.brownianGenerationCylinder,
    hmu.attractor.generationCylinder_eq_affineTimeCompact S k w,
    affineBrownianCompactPiece, System.IsNatural.compactAttractor,
    Real.coe_toNNReal _ (S.generationRatio_pos k w).le,
    ← S.tubeRadiusReal_sub_generationHalfLogRatio k w v] using hlaw

omit [Nonempty iota] in
/-- Profile-scale Brownian scaling for an arbitrary generation cylinder. -/
theorem IsPlanarBrownian.identDistrib_normalizedTubeMass_brownianGenerationCylinder
    [IsProbabilityMeasure P] (hW : IsPlanarBrownian W P)
    {K : Set ℝ} {s : ℝ} {mu : Measure ℝ}
    (hmu : S.IsNatural K s mu) (k : ℕ)
    (w : GenerationWord iota k) (v : ℝ) :
    IdentDistrib
      (fun omega => normalizedTubeMass s v
        (hmu.attractor.brownianGenerationCylinder S W omega k w))
      (fun omega => S.generationWeight s k w *
        brownianTubeProfile W hmu.compactAttractor s
          (v - S.generationHalfLogRatio k w) omega) P P := by
  let X : Omega → ℝ := fun omega =>
    tubeMass (tubeRadiusReal v)
      (hmu.attractor.brownianGenerationCylinder S W omega k w)
  let Y : Omega → ℝ := fun omega => S.generationRatio k w *
    tubeMass (tubeRadiusReal (v - S.generationHalfLogRatio k w))
      (brownianImage W hmu.compactAttractor omega)
  have hX : AEMeasurable X P :=
    (continuous_tubeMass (tubeRadiusReal_pos v)).measurable.comp_aemeasurable
      (hW.aemeasurable_brownianImage
        (hmu.attractor.generationCylinder S k w))
  have hY : AEMeasurable Y P :=
    (continuous_const.mul
      (continuous_tubeMass
        (tubeRadiusReal_pos (v - S.generationHalfLogRatio k w)))).measurable
      |>.comp_aemeasurable (hW.aemeasurable_brownianImage hmu.compactAttractor)
  have hmass : IdentDistrib X Y P P :=
    ⟨hX, hY, hW.map_tubeMass_brownianGenerationCylinder_eq
      S hmu k w v⟩
  have hscaled := hmass.const_mul (Real.exp (tubeExponent s * v))
  simpa only [X, Y, normalizedTubeMass, brownianTubeProfile, ← mul_assoc,
    S.exp_tubeExponent_mul_generationRatio s k w v] using hscaled

end Brownian

end

end BrownianImages
