/-
`thm:neighbourhood-renewal`: the non-arithmetic renewal-limit mechanism for the mean
Brownian tube profile.

The expectation identity in `MinkowskiTubeRenewal` has half-logarithmic steps
`beta_i = log(1 / r_i) / 2`.  Doubling logarithmic scale turns it into the renewal
law already treated in `KeyRenewalFourier`.  A cutoff is essential: the normalised
tube profile need not vanish at `-infinity`, whereas the key renewal theorem needs
that boundary condition.  The cutoff is zero on the negative half-line and one
above `1`, so it changes neither the desired limit nor the tail renewal equation.

This file makes the remaining analytic input exact.  It is direct Riemann
integrability of the cutoff forcing, which consists of a bounded boundary term on
a finite interval and the negative expected multiple-counting defect on the tail.
No renewal limit is asserted from integrability of the defect alone.
-/
import BrownianImages.KeyRenewalFourier
import BrownianImages.MinkowskiTubeRenewal

namespace BrownianImages

open Filter MeasureTheory ProbabilityTheory Set TopologicalSpace
open scoped ENNReal NNReal Topology

noncomputable section

namespace System

variable {iota : Type*} [Fintype iota] (S : System iota)

/-! ### Arithmetic of the half-logarithmic steps -/

/-- Multiplication by two sends the additive subgroup generated by the
half-logarithmic steps into the subgroup generated by the full logarithmic steps. -/
theorem two_mul_mem_logRatio_closure_of_mem_halfLogRatio_closure
    {x : Real}
    (hx : x ∈ AddSubgroup.closure (Set.range S.halfLogRatio)) :
    2 * x ∈ AddSubgroup.closure (Set.range S.logRatio) := by
  refine AddSubgroup.closure_induction (p := fun x _ =>
    2 * x ∈ AddSubgroup.closure (Set.range S.logRatio)) ?_ ?_ ?_ ?_ hx
  · rintro x ⟨i, rfl⟩
    have hmem : S.logRatio i ∈ AddSubgroup.closure (Set.range S.logRatio) :=
      AddSubgroup.subset_closure ⟨i, rfl⟩
    convert hmem using 1
    simp only [halfLogRatio]
    ring
  · simp
  · intro x y _ _ hx hy
    convert (AddSubgroup.closure (Set.range S.logRatio)).add_mem hx hy using 1
    ring
  · intro x _ hx
    convert (AddSubgroup.closure (Set.range S.logRatio)).neg_mem hx using 1
    ring

/-- Multiplication by one half sends the subgroup generated by the full logarithmic
steps into the subgroup generated by the half-logarithmic steps. -/
theorem half_mul_mem_halfLogRatio_closure_of_mem_logRatio_closure
    {x : Real}
    (hx : x ∈ AddSubgroup.closure (Set.range S.logRatio)) :
    (1 / 2 : Real) * x ∈ AddSubgroup.closure (Set.range S.halfLogRatio) := by
  refine AddSubgroup.closure_induction (p := fun x _ =>
    (1 / 2 : Real) * x ∈ AddSubgroup.closure (Set.range S.halfLogRatio)) ?_ ?_ ?_ ?_ hx
  · rintro x ⟨i, rfl⟩
    exact AddSubgroup.subset_closure ⟨i, rfl⟩
  · simp
  · intro x y _ _ hx hy
    convert (AddSubgroup.closure (Set.range S.halfLogRatio)).add_mem hx hy using 1
    ring
  · intro x _ hx
    convert (AddSubgroup.closure (Set.range S.halfLogRatio)).neg_mem hx using 1
    ring

/-- Passing from logarithmic steps to half-logarithmic steps does not change the
non-arithmetic condition. -/
theorem tubeNonArithmetic_iff_nonArithmetic :
    S.TubeNonArithmetic ↔ S.NonArithmetic := by
  constructor
  · intro hna
    refine (Function.Surjective.denseRange
      (f := fun x : Real => 2 * x) (fun y => ⟨y / 2, by ring⟩)).dense_of_mapsTo
        (by fun_prop) hna ?_
    intro x hx
    exact S.two_mul_mem_logRatio_closure_of_mem_halfLogRatio_closure hx
  · intro hna
    refine (Function.Surjective.denseRange
      (f := fun x : Real => (1 / 2 : Real) * x) (fun y => ⟨2 * y, by ring⟩)).dense_of_mapsTo
        (by fun_prop) hna ?_
    intro x hx
    exact S.half_mul_mem_halfLogRatio_closure_of_mem_logRatio_closure hx

/-! ### Cutoff and rescaling -/

/-- The fixed continuous renewal cutoff.  It is zero on `(-infinity, 0]` and one
on `[1, infinity)`. -/
noncomputable def tubeRenewalCutoff (y : Real) : Real :=
  max 0 (min 1 y)

theorem continuous_tubeRenewalCutoff : Continuous tubeRenewalCutoff := by
  exact continuous_const.max (continuous_const.min continuous_id)

theorem tubeRenewalCutoff_nonneg (y : Real) : 0 ≤ tubeRenewalCutoff y := by
  simp [tubeRenewalCutoff]

theorem tubeRenewalCutoff_le_one (y : Real) : tubeRenewalCutoff y ≤ 1 := by
  simp [tubeRenewalCutoff]

theorem tubeRenewalCutoff_eq_zero_of_nonpos {y : Real} (hy : y ≤ 0) :
    tubeRenewalCutoff y = 0 := by
  simp [tubeRenewalCutoff, hy]

theorem tubeRenewalCutoff_eq_one_of_one_le {y : Real} (hy : 1 ≤ y) :
    tubeRenewalCutoff y = 1 := by
  simp [tubeRenewalCutoff, hy]

open _root_.AbsorptionCutoff.Renewal in
/-- A one-sided exponential tail is directly Riemann integrable.  The function may
be arbitrary but uniformly bounded on the finite transition region; it only has to
vanish on the negative half-line and decay exponentially eventually. -/
theorem driNorm_enorm_ne_top_of_zero_left_of_bounded_of_exp_decay
    {f : Real → Real} {A C gamma L : Real}
    (hA : 0 ≤ A) (hC : 0 ≤ C) (hgamma : 0 < gamma) (hL : 0 ≤ L)
    (hzero : ∀ x : Real, x ≤ 0 → f x = 0)
    (hbound : ∀ x : Real, |f x| ≤ A)
    (htail : ∀ x : Real, L ≤ x → |f x| ≤ C * Real.exp (-gamma * x)) :
    driNorm (fun x => ‖f x‖ₑ) ≠ ∞ := by
  let D : Real := (A + C) * Real.exp (gamma * L)
  have hD : 0 ≤ D := mul_nonneg (add_nonneg hA hC) (Real.exp_pos _).le
  have hCD : C ≤ D := by
    calc
      C ≤ A + C := by linarith
      _ ≤ (A + C) * Real.exp (gamma * L) :=
        le_mul_of_one_le_right (add_nonneg hA hC)
          (Real.one_le_exp (mul_nonneg hgamma.le hL))
  let a : Int → Real := fun k =>
    if k < 0 then 0 else D * Real.exp (-gamma * (k : Real))
  have ha : ∀ k, 0 ≤ a k := by
    intro k
    simp only [a]
    split
    · exact le_rfl
    · positivity
  have hcell : ∀ k : Int,
      cellSup (fun x => ‖f x‖ₑ) k ≤ ENNReal.ofReal (a k) := by
    intro k
    refine iSup₂_le fun x hx => ?_
    rw [Set.mem_Icc] at hx
    simp only [a]
    by_cases hk : k < 0
    · rw [if_pos hk]
      have hk1 : k + 1 ≤ 0 := by omega
      have hx0 : x ≤ 0 := hx.2.trans (by exact_mod_cast hk1)
      rw [hzero x hx0]
      simp
    · rw [if_neg hk, Real.enorm_eq_ofReal_abs]
      apply ENNReal.ofReal_le_ofReal
      by_cases hxL : L ≤ x
      · have hexp : Real.exp (-gamma * x) ≤
            Real.exp (-gamma * (k : Real)) := by
          apply Real.exp_le_exp.mpr
          have hkx : (k : Real) ≤ x := hx.1
          nlinarith
        calc
          |f x| ≤ C * Real.exp (-gamma * x) := htail x hxL
          _ ≤ C * Real.exp (-gamma * (k : Real)) :=
            mul_le_mul_of_nonneg_left hexp hC
          _ ≤ D * Real.exp (-gamma * (k : Real)) :=
            mul_le_mul_of_nonneg_right hCD (Real.exp_pos _).le
      · have hk0 : (0 : Real) ≤ (k : Real) := by
          exact_mod_cast (not_lt.mp hk)
        have hkL : (k : Real) < L := lt_of_le_of_lt hx.1 (lt_of_not_ge hxL)
        have hexp1 : 1 ≤ Real.exp (gamma * (L - (k : Real))) :=
          Real.one_le_exp (mul_nonneg hgamma.le (sub_nonneg.mpr hkL.le))
        calc
          |f x| ≤ A := hbound x
          _ ≤ A + C := by linarith
          _ ≤ (A + C) * Real.exp (gamma * (L - (k : Real))) :=
            le_mul_of_one_le_right (add_nonneg hA hC) hexp1
          _ = D * Real.exp (-gamma * (k : Real)) := by
            simp only [D]
            rw [mul_assoc, ← Real.exp_add]
            congr 2
            ring
  have hasum : Summable a := by
    refine Summable.of_nat_of_neg ?_ ?_
    · have hgeo : Summable fun n : Nat =>
          D * Real.exp (-gamma) ^ n := by
        exact Summable.mul_left D
          (summable_geometric_of_lt_one (Real.exp_pos _).le
            (Real.exp_lt_one_iff.mpr (by linarith)))
      refine hgeo.congr fun n => ?_
      simp only [a]
      congr 1
      rw [← Real.exp_nat_mul]
      congr 1
      push_cast
      ring
    · refine summable_of_ne_finset_zero (s := {0}) fun n hn => ?_
      have hn0 : n ≠ 0 := by simpa using hn
      have hnpos : 0 < n := Nat.pos_of_ne_zero hn0
      have hneg : (-(n : Int)) < 0 := by omega
      change (if (-(n : Int)) < 0 then 0 else
        D * Real.exp (-gamma * ((-(n : Int) : Int) : Real))) = 0
      rw [if_pos hneg]
  rw [driNorm_def]
  refine ne_top_of_le_ne_top ?_ (ENNReal.tsum_le_tsum hcell)
  rw [← ENNReal.ofReal_tsum_of_nonneg ha hasum]
  exact ENNReal.ofReal_ne_top

/-- The mean profile on doubled logarithmic scale, with the renewal cutoff inserted. -/
noncomputable def cutoffRescaledTubeProfile (m : Real → Real) (y : Real) : Real :=
  tubeRenewalCutoff y * m (y / 2)

/-- The exact forcing of the cutoff profile for the full-logarithmic renewal law. -/
noncomputable def cutoffTubeRenewalForcing (s : Real) (m : Real → Real)
    (y : Real) : Real :=
  cutoffRescaledTubeProfile m y -
    S.renewalConv s (cutoffRescaledTubeProfile m) y

theorem continuous_cutoffRescaledTubeProfile {m : Real → Real}
    (hm : Continuous m) : Continuous (cutoffRescaledTubeProfile m) := by
  exact continuous_tubeRenewalCutoff.mul
    (hm.comp (continuous_id.div_const 2))

theorem continuous_cutoffTubeRenewalForcing {s : Real} {m : Real → Real}
    (hm : Continuous m) : Continuous (S.cutoffTubeRenewalForcing s m) := by
  have hcut : Continuous (cutoffRescaledTubeProfile m) :=
    continuous_cutoffRescaledTubeProfile hm
  refine hcut.sub (continuous_finsetSum _ fun i _ => ?_)
  exact continuous_const.mul
    (hcut.comp (continuous_id.sub continuous_const))

/-- The cutoff profile is uniformly bounded if the original mean profile is bounded
on nonnegative logarithmic scales. -/
theorem abs_cutoffRescaledTubeProfile_le {m : Real → Real} {A : Real}
    (hA : ∀ v : Real, 0 ≤ v → |m v| ≤ A) (y : Real) :
    |cutoffRescaledTubeProfile m y| ≤ A := by
  by_cases hy : y ≤ 0
  · rw [cutoffRescaledTubeProfile, tubeRenewalCutoff_eq_zero_of_nonpos hy,
      zero_mul, abs_zero]
    exact (abs_nonneg (m 0)).trans (hA 0 le_rfl)
  · have hy0 : 0 ≤ y / 2 := div_nonneg (le_of_not_ge hy) (by norm_num)
    rw [cutoffRescaledTubeProfile, abs_mul,
      abs_of_nonneg (tubeRenewalCutoff_nonneg y)]
    exact (mul_le_mul_of_nonneg_left (hA (y / 2) hy0)
      (tubeRenewalCutoff_nonneg y)).trans
      (mul_le_of_le_one_left ((abs_nonneg (m 0)).trans (hA 0 le_rfl))
        (tubeRenewalCutoff_le_one y))

/-- The cutoff profile vanishes at the lower end of logarithmic scale. -/
theorem tendsto_cutoffRescaledTubeProfile_atBot (m : Real → Real) :
    Tendsto (cutoffRescaledTubeProfile m) atBot (nhds 0) := by
  apply tendsto_const_nhds.congr'
  filter_upwards [eventually_le_atBot (0 : Real)] with y hy
  simp [cutoffRescaledTubeProfile, tubeRenewalCutoff_eq_zero_of_nonpos hy]

/-- Above the cutoff transition, the cutoff profile is exactly the original profile
on doubled logarithmic scale. -/
theorem cutoffRescaledTubeProfile_eq_of_one_le {m : Real → Real} {y : Real}
    (hy : 1 ≤ y) : cutoffRescaledTubeProfile m y = m (y / 2) := by
  rw [cutoffRescaledTubeProfile, tubeRenewalCutoff_eq_one_of_one_le hy, one_mul]

/-- The full-logarithmic convolution of a doubled-scale profile is the
half-logarithmic tube convolution at the original scale. -/
theorem renewalConv_rescaled_eq_tubeRenewalConv (s y : Real) (m : Real → Real) :
    S.renewalConv s (fun x => m (x / 2)) y =
      S.tubeRenewalConv s m (y / 2) := by
  unfold renewalConv tubeRenewalConv tubeWeight
  apply Finset.sum_congr rfl
  intro i _
  congr 2
  rw [halfLogRatio]
  ring_nf

/-- The cutoff forcing vanishes on the negative half-line.  All renewal steps are
positive, so every delayed cutoff profile vanishes there as well. -/
theorem cutoffTubeRenewalForcing_eq_zero_of_nonpos
    {s : Real} {m : Real → Real} {y : Real} (hy : y ≤ 0) :
    S.cutoffTubeRenewalForcing s m y = 0 := by
  have hdelay : ∀ i : iota,
      cutoffRescaledTubeProfile m (y - S.logRatio i) = 0 := by
    intro i
    rw [cutoffRescaledTubeProfile,
      tubeRenewalCutoff_eq_zero_of_nonpos (by linarith [S.logRatio_pos i]),
      zero_mul]
  rw [cutoffTubeRenewalForcing, cutoffRescaledTubeProfile,
    tubeRenewalCutoff_eq_zero_of_nonpos hy, zero_mul, renewalConv]
  simp only [hdelay, mul_zero, Finset.sum_const_zero, sub_zero]

/-- A bound on the cutoff profile gives twice that bound for its renewal forcing. -/
theorem abs_cutoffTubeRenewalForcing_le
    {s : Real} (hdim : S.IsDimension s) {m : Real → Real} {A : Real}
    (hA : ∀ v : Real, 0 ≤ v → |m v| ≤ A) (y : Real) :
    |S.cutoffTubeRenewalForcing s m y| ≤ 2 * A := by
  have hA0 : 0 ≤ A := (abs_nonneg (m 0)).trans (hA 0 le_rfl)
  have hcut : ∀ x : Real, |cutoffRescaledTubeProfile m x| ≤ A :=
    abs_cutoffRescaledTubeProfile_le hA
  have hconv : |S.renewalConv s (cutoffRescaledTubeProfile m) y| ≤ A := by
    rw [renewalConv]
    calc
      |∑ i, S.ratio i ^ s * cutoffRescaledTubeProfile m (y - S.logRatio i)| ≤
          ∑ i, |S.ratio i ^ s * cutoffRescaledTubeProfile m (y - S.logRatio i)| :=
        Finset.abs_sum_le_sum_abs _ _
      _ ≤ ∑ i, S.ratio i ^ s * A := by
        apply Finset.sum_le_sum
        intro i _
        rw [abs_mul, abs_of_nonneg
          (Real.rpow_pos_of_pos (S.ratio_pos i) s).le]
        exact mul_le_mul_of_nonneg_left (hcut _)
          (Real.rpow_pos_of_pos (S.ratio_pos i) s).le
      _ = A := by rw [← Finset.sum_mul, hdim, one_mul]
  rw [cutoffTubeRenewalForcing]
  calc
    |cutoffRescaledTubeProfile m y -
        S.renewalConv s (cutoffRescaledTubeProfile m) y| ≤
        |cutoffRescaledTubeProfile m y| +
          |S.renewalConv s (cutoffRescaledTubeProfile m) y| := abs_sub _ _
    _ ≤ A + A := add_le_add (hcut y) hconv
    _ = 2 * A := by ring

/-- A convenient finite threshold beyond which the cutoff and all of its delayed
copies are identically one. -/
noncomputable def tubeRenewalTailThreshold : Real :=
  1 + ∑ i, |S.logRatio i|

theorem one_add_logRatio_le_tubeRenewalTailThreshold (i : iota) :
    1 + S.logRatio i ≤ S.tubeRenewalTailThreshold := by
  unfold tubeRenewalTailThreshold
  gcongr
  calc
    S.logRatio i ≤ |S.logRatio i| := le_abs_self _
    _ ≤ ∑ j, |S.logRatio j| :=
      Finset.single_le_sum (f := fun j : iota => |S.logRatio j|)
        (fun j _ => abs_nonneg _) (Finset.mem_univ i)

theorem tubeRenewalTailThreshold_nonneg : 0 ≤ S.tubeRenewalTailThreshold := by
  unfold tubeRenewalTailThreshold
  positivity

/-- On the tail, where the cutoff and all its delayed copies equal one, the cutoff
forcing is the negative multiple-counting defect from the tube renewal equation. -/
theorem cutoffTubeRenewalForcing_eq_neg_of_tail
    [Nonempty iota] {s : Real} {m d : Real → Real}
    (hrenew : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      m v = S.tubeRenewalConv s m v - d v)
    {y : Real} (hy : ∀ i : iota, 1 + S.logRatio i ≤ y) :
    S.cutoffTubeRenewalForcing s m y = -d (y / 2) := by
  have hy1 : 1 ≤ y := by
    obtain ⟨i⟩ := ‹Nonempty iota›
    linarith [hy i, S.logRatio_pos i]
  have hdelay : ∀ i : iota,
      cutoffRescaledTubeProfile m (y - S.logRatio i) =
        m ((y - S.logRatio i) / 2) := by
    intro i
    apply cutoffRescaledTubeProfile_eq_of_one_le
    linarith [hy i]
  rw [cutoffTubeRenewalForcing,
    cutoffRescaledTubeProfile_eq_of_one_le hy1, renewalConv]
  simp_rw [hdelay]
  have hconv := S.renewalConv_rescaled_eq_tubeRenewalConv s y m
  unfold renewalConv at hconv
  rw [hconv, hrenew (y / 2) (fun i => by
    rw [halfLogRatio]
    linarith [hy i])]
  ring

/-- Exponential decay of the expected tube defect implies direct Riemann
integrability of the cutoff forcing.  The finite cutoff boundary layer is controlled
only by boundedness of the mean profile. -/
theorem driNorm_cutoffTubeRenewalForcing_ne_top_of_exp_defect
    [Nonempty iota] {s : Real} (hdim : S.IsDimension s)
    {m d : Real → Real} {A C gamma : Real} (hC : 0 ≤ C)
    (hgamma : 0 < gamma)
    (hA : ∀ v : Real, 0 ≤ v → |m v| ≤ A)
    (hrenew : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      m v = S.tubeRenewalConv s m v - d v)
    (hdefect : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      0 ≤ d v ∧ d v ≤ C * Real.exp (-gamma * v)) :
    AbsorptionCutoff.Renewal.driNorm
      (fun y => ‖S.cutoffTubeRenewalForcing s m y‖ₑ) ≠ ∞ := by
  have hA0 : 0 ≤ A := (abs_nonneg (m 0)).trans (hA 0 le_rfl)
  apply driNorm_enorm_ne_top_of_zero_left_of_bounded_of_exp_decay
    (A := 2 * A) (C := C) (gamma := gamma / 2)
    (L := S.tubeRenewalTailThreshold)
    (mul_nonneg (by norm_num) hA0) hC (half_pos hgamma)
    S.tubeRenewalTailThreshold_nonneg
  · intro y hy
    exact S.cutoffTubeRenewalForcing_eq_zero_of_nonpos hy
  · intro y
    exact S.abs_cutoffTubeRenewalForcing_le hdim hA y
  · intro y hy
    have hy0 : 0 ≤ y := S.tubeRenewalTailThreshold_nonneg.trans hy
    have hvsteps : ∀ i : iota, S.halfLogRatio i ≤ y / 2 := by
      intro i
      rw [halfLogRatio]
      linarith [S.one_add_logRatio_le_tubeRenewalTailThreshold i]
    rw [S.cutoffTubeRenewalForcing_eq_neg_of_tail hrenew
      (fun i => (S.one_add_logRatio_le_tubeRenewalTailThreshold i).trans hy),
      abs_neg, abs_of_nonneg (hdefect (y / 2) hvsteps).1]
    have htail := (hdefect (y / 2) hvsteps).2
    convert htail using 1
    congr 2
    ring

/-! ### Non-arithmetic limit -/

/-- The non-arithmetic key renewal theorem for a cutoff tube profile.  The only
renewal-specific analytic hypothesis left is direct Riemann integrability of the
cutoff forcing.  Continuity and a right-half-line bound on the mean profile provide
the other hypotheses required by the key renewal theorem. -/
theorem tendsto_mean_of_tubeNonArithmetic_of_cutoffForcing_dri
    [Nonempty iota] {s : Real} (hdim : S.IsDimension s)
    (hna : S.TubeNonArithmetic) {m : Real → Real} {A : Real}
    (hm : Continuous m) (hA : ∀ v : Real, 0 ≤ v → |m v| ≤ A)
    (hdri : AbsorptionCutoff.Renewal.driNorm
      (fun y => ‖S.cutoffTubeRenewalForcing s m y‖ₑ) ≠ ∞) :
    Tendsto m atTop
      (nhds ((S.renewalMean s)⁻¹ *
        ∫ y : Real, S.cutoffTubeRenewalForcing s m y)) := by
  let h : Real → Real := cutoffRescaledTubeProfile m
  let z : Real → Real := S.cutoffTubeRenewalForcing s m
  have hh : Continuous h := continuous_cutoffRescaledTubeProfile hm
  have hz : Continuous z := S.continuous_cutoffTubeRenewalForcing hm
  have hbound : ∀ y, |h y| ≤ A := abs_cutoffRescaledTubeProfile_le hA
  have hbot : Tendsto h atBot (nhds 0) := tendsto_cutoffRescaledTubeProfile_atBot m
  have hrec : ∀ y, h y = S.renewalConv s h y + z y := by
    intro y
    simp only [h, z, cutoffTubeRenewalForcing]
    ring
  have hlim : Tendsto h atTop
      (nhds ((S.renewalMean s)⁻¹ * ∫ y : Real, z y)) :=
    S.tendsto_of_renewalEquation hdim
      ((S.tubeNonArithmetic_iff_nonArithmetic).mp hna)
      hz hdri hh hbound hbot hrec
  have hscale : Tendsto (fun v : Real => 2 * v) atTop atTop :=
    tendsto_id.const_mul_atTop (by norm_num)
  have hcomp := hlim.comp hscale
  have heq : (fun v : Real => h (2 * v)) =ᶠ[atTop] m := by
    filter_upwards [eventually_ge_atTop (1 / 2 : Real)] with v hv
    simp only [h]
    rw [cutoffRescaledTubeProfile_eq_of_one_le (by linarith)]
    congr 1
    ring
  exact hcomp.congr' heq

/-- Paper-shaped form of the preceding theorem.  Besides the limit, it records that
the directly Riemann integrable cutoff forcing is exactly the negative expected tube
defect after the finite cutoff boundary layer. -/
theorem tendsto_mean_and_forcing_eq_neg_defect_of_tubeNonArithmetic
    [Nonempty iota] {s : Real} (hdim : S.IsDimension s)
    (hna : S.TubeNonArithmetic) {m d : Real → Real} {A : Real}
    (hm : Continuous m) (hA : ∀ v : Real, 0 ≤ v → |m v| ≤ A)
    (hrenew : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      m v = S.tubeRenewalConv s m v - d v)
    (hdri : AbsorptionCutoff.Renewal.driNorm
      (fun y => ‖S.cutoffTubeRenewalForcing s m y‖ₑ) ≠ ∞) :
    Tendsto m atTop
        (nhds ((S.renewalMean s)⁻¹ *
          ∫ y : Real, S.cutoffTubeRenewalForcing s m y)) ∧
      ∀ y : Real, (∀ i : iota, 1 + S.logRatio i ≤ y) →
        S.cutoffTubeRenewalForcing s m y = -d (y / 2) := by
  exact ⟨S.tendsto_mean_of_tubeNonArithmetic_of_cutoffForcing_dri
      hdim hna hm hA hdri,
    fun y hy => S.cutoffTubeRenewalForcing_eq_neg_of_tail hrenew hy⟩

/-- Non-arithmetic renewal limit with the direct Riemann integrability obligation
discharged by an exponentially decaying tube defect. -/
theorem tendsto_mean_and_forcing_eq_neg_defect_of_exp_defect
    [Nonempty iota] {s : Real} (hdim : S.IsDimension s)
    (hna : S.TubeNonArithmetic) {m d : Real → Real} {A C gamma : Real}
    (hm : Continuous m) (hC : 0 ≤ C) (hgamma : 0 < gamma)
    (hA : ∀ v : Real, 0 ≤ v → |m v| ≤ A)
    (hrenew : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      m v = S.tubeRenewalConv s m v - d v)
    (hdefect : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      0 ≤ d v ∧ d v ≤ C * Real.exp (-gamma * v)) :
    Tendsto m atTop
        (nhds ((S.renewalMean s)⁻¹ *
          ∫ y : Real, S.cutoffTubeRenewalForcing s m y)) ∧
      ∀ y : Real, (∀ i : iota, 1 + S.logRatio i ≤ y) →
        S.cutoffTubeRenewalForcing s m y = -d (y / 2) := by
  apply S.tendsto_mean_and_forcing_eq_neg_defect_of_tubeNonArithmetic
    hdim hna hm hA hrenew
  exact S.driNorm_cutoffTubeRenewalForcing_ne_top_of_exp_defect
    hdim hC hgamma hA hrenew hdefect

end System

/-! ### Mean Brownian tube profile -/

/-- The mean Brownian tube profile is nonnegative at every logarithmic scale. -/
theorem meanBrownianTubeProfile_nonneg
    {Omega : Type*} [MeasurableSpace Omega] (W : NNReal → Omega → Plane)
    (P : Measure Omega) (K : NonemptyCompacts Real) (s v : Real) :
    0 ≤ meanBrownianTubeProfile W P K s v := by
  apply integral_nonneg
  intro omega
  exact normalizedTubeMass_nonneg s v (brownianImage W K omega)

/-- The non-arithmetic mean Brownian tube profile converges once its continuity,
right-half-line bounds, exact renewal equation, and the direct Riemann integrability
of the cutoff forcing have been supplied.  A positive lower bound passes to the
renewal limit, so the resulting constant is strictly positive.

The cutoff forcing is not an extra probabilistic object: by
`System.cutoffTubeRenewalForcing_eq_neg_of_tail` it is the negative expected
multiple-counting defect away from one finite boundary layer. -/
theorem System.IsNatural.meanBrownianTubeProfile_tendsto_of_cutoffForcing_dri
    {Omega iota : Type*} [MeasurableSpace Omega] [Fintype iota] [Nonempty iota]
    {P : Measure Omega} [IsProbabilityMeasure P]
    {W : NNReal → Omega → Plane} (S : System iota)
    {K : Set Real} {s : Real} {mu : Measure Real}
    (hmu : S.IsNatural K s mu) (hdim : S.IsDimension s)
    (hna : S.TubeNonArithmetic)
    (hm : Continuous
      (meanBrownianTubeProfile W P hmu.compactAttractor s))
    {c A : Real} (hc : 0 < c)
    (hbounds : ∀ v : Real, 0 ≤ v →
      c ≤ meanBrownianTubeProfile W P hmu.compactAttractor s v ∧
      |meanBrownianTubeProfile W P hmu.compactAttractor s v| ≤ A)
    (hrenew : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      meanBrownianTubeProfile W P hmu.compactAttractor s v =
        S.tubeRenewalConv s
          (meanBrownianTubeProfile W P hmu.compactAttractor s) v -
          hmu.meanBrownianTubeDefectProfile S W P v)
    (hdri : AbsorptionCutoff.Renewal.driNorm
      (fun y => ‖S.cutoffTubeRenewalForcing s
        (meanBrownianTubeProfile W P hmu.compactAttractor s) y‖ₑ) ≠ ∞) :
    ∃ CK : Real, 0 < CK ∧
      Tendsto (meanBrownianTubeProfile W P hmu.compactAttractor s)
        atTop (nhds CK) := by
  let m : Real → Real := meanBrownianTubeProfile W P hmu.compactAttractor s
  let d : Real → Real := hmu.meanBrownianTubeDefectProfile S W P
  let CK : Real := (S.renewalMean s)⁻¹ *
    ∫ y : Real, S.cutoffTubeRenewalForcing s m y
  have hpackage := S.tendsto_mean_and_forcing_eq_neg_defect_of_tubeNonArithmetic
    hdim hna (m := m) (d := d) hm (fun v hv => (hbounds v hv).2)
      (fun v hv => hrenew v hv) hdri
  have hlim : Tendsto m atTop (nhds CK) := hpackage.1
  have hcCK : c ≤ CK := ge_of_tendsto hlim (by
    filter_upwards [eventually_ge_atTop (0 : Real)] with v hv
    exact (hbounds v hv).1)
  exact ⟨CK, lt_of_lt_of_le hc hcCK, hlim⟩

/-- Non-arithmetic mean-profile convergence from the paper's exponential defect
estimate.  Direct Riemann integrability is no longer a hypothesis here: the preceding
one-sided exponential-tail lemma proves it from boundedness of the mean profile and
decay of the expected multiple-counting defect. -/
theorem System.IsNatural.meanBrownianTubeProfile_tendsto_of_exp_defect
    {Omega iota : Type*} [MeasurableSpace Omega] [Fintype iota] [Nonempty iota]
    {P : Measure Omega} [IsProbabilityMeasure P]
    {W : NNReal → Omega → Plane} (S : System iota)
    {K : Set Real} {s : Real} {mu : Measure Real}
    (hmu : S.IsNatural K s mu) (hdim : S.IsDimension s)
    (hna : S.TubeNonArithmetic)
    (hm : Continuous
      (meanBrownianTubeProfile W P hmu.compactAttractor s))
    {c A C gamma : Real} (hc : 0 < c) (hC : 0 ≤ C)
    (hgamma : 0 < gamma)
    (hbounds : ∀ v : Real, 0 ≤ v →
      c ≤ meanBrownianTubeProfile W P hmu.compactAttractor s v ∧
      meanBrownianTubeProfile W P hmu.compactAttractor s v ≤ A)
    (hrenew : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      meanBrownianTubeProfile W P hmu.compactAttractor s v =
        S.tubeRenewalConv s
          (meanBrownianTubeProfile W P hmu.compactAttractor s) v -
          hmu.meanBrownianTubeDefectProfile S W P v)
    (hdefect : ∀ v : Real, (∀ i : iota, S.halfLogRatio i ≤ v) →
      0 ≤ hmu.meanBrownianTubeDefectProfile S W P v ∧
      hmu.meanBrownianTubeDefectProfile S W P v ≤
        C * Real.exp (-gamma * v)) :
    ∃ CK : Real, 0 < CK ∧
      Tendsto (meanBrownianTubeProfile W P hmu.compactAttractor s)
        atTop (nhds CK) := by
  let m : Real → Real := meanBrownianTubeProfile W P hmu.compactAttractor s
  let d : Real → Real := hmu.meanBrownianTubeDefectProfile S W P
  let CK : Real := (S.renewalMean s)⁻¹ *
    ∫ y : Real, S.cutoffTubeRenewalForcing s m y
  have hAabs : ∀ v : Real, 0 ≤ v → |m v| ≤ A := by
    intro v hv
    rw [abs_of_nonneg (meanBrownianTubeProfile_nonneg W P
      hmu.compactAttractor s v)]
    exact (hbounds v hv).2
  have hpackage :=
    S.tendsto_mean_and_forcing_eq_neg_defect_of_exp_defect
      hdim hna (m := m) (d := d) hm hC hgamma hAabs
      (fun v hv => hrenew v hv) (fun v hv => hdefect v hv)
  have hlim : Tendsto m atTop (nhds CK) := hpackage.1
  have hcCK : c ≤ CK := ge_of_tendsto hlim (by
    filter_upwards [eventually_ge_atTop (0 : Real)] with v hv
    exact (hbounds v hv).1)
  exact ⟨CK, lt_of_lt_of_le hc hcCK, hlim⟩

/-- Complete non-arithmetic renewal assembly from profile bounds and the uniform
first-level overlap estimate.  The overlap theorem supplies both integrability and
exponential decay of the expected multiple-counting defect; delayed profile
integrability supplies the exact renewal equation.  Thus, after the tube-moment and
tube-overlap estimates, continuity of the mean profile is the only additional
analytic input in this statement. -/
theorem System.IsNatural.meanBrownianTubeProfile_tendsto_of_pairwise_overlap
    {Omega iota : Type*} [MeasurableSpace Omega] [Fintype iota] [Nonempty iota]
    {P : Measure Omega} [IsProbabilityMeasure P]
    {W : NNReal → Omega → Plane} (hW : IsPlanarBrownian W P)
    (S : System iota) {K : Set Real} {s : Real} {mu : Measure Real}
    (hmu : S.IsNatural K s mu) (hdim : S.IsDimension s)
    (hs1 : s < 1) (hna : S.TubeNonArithmetic)
    (hm : Continuous
      (meanBrownianTubeProfile W P hmu.compactAttractor s))
    {c A C : Real} (hc : 0 < c) (hC : 0 ≤ C)
    (hint : ∀ v : Real, 0 ≤ v →
      Integrable (brownianTubeProfile W hmu.compactAttractor s v) P)
    (hbounds : ∀ v : Real, 0 ≤ v →
      c ≤ meanBrownianTubeProfile W P hmu.compactAttractor s v ∧
      meanBrownianTubeProfile W P hmu.compactAttractor s v ≤ A)
    (hpair : ∀ v : Real, 0 ≤ v → ∀ i j : iota, i ≠ j →
      Integrable (fun omega => tubeOverlapArea (tubeRadiusReal v)
        (hmu.brownianFirstLevelPiece S W omega i)
        (hmu.brownianFirstLevelPiece S W omega j)) P ∧
      (∫ omega, tubeOverlapArea (tubeRadiusReal v)
        (hmu.brownianFirstLevelPiece S W omega i)
        (hmu.brownianFirstLevelPiece S W omega j) ∂P) ≤
          C * tubeRadiusReal v ^ (2 * tubeExponent s)) :
    ∃ CK : Real, 0 < CK ∧
      Tendsto (meanBrownianTubeProfile W P hmu.compactAttractor s)
        atTop (nhds CK) := by
  let D : Real := ((Fintype.card iota : Real) ^ 2 / 2) * C
  have hD : 0 ≤ D := mul_nonneg (by positivity) hC
  have hgamma : 0 < tubeExponent s := by
    unfold tubeExponent
    linarith
  have hrenewal : ∀ v : Real,
      (∀ i : iota, S.halfLogRatio i ≤ v) →
      Integrable (brownianTubeProfile W hmu.compactAttractor s v) P ∧
      meanBrownianTubeProfile W P hmu.compactAttractor s v =
        S.tubeRenewalConv s
          (meanBrownianTubeProfile W P hmu.compactAttractor s) v -
          hmu.meanBrownianTubeDefectProfile S W P v ∧
      0 ≤ hmu.meanBrownianTubeDefectProfile S W P v ∧
      hmu.meanBrownianTubeDefectProfile S W P v ≤
        D * Real.exp (-tubeExponent s * v) := by
    intro v hvsteps
    obtain ⟨i0⟩ := ‹Nonempty iota›
    have hv0 : 0 ≤ v := (S.halfLogRatio_pos i0).le.trans (hvsteps i0)
    have hdelayed : ∀ i,
        Integrable (brownianTubeProfile W hmu.compactAttractor s
          (v - S.halfLogRatio i)) P := by
      intro i
      exact hint (v - S.halfLogRatio i) (sub_nonneg.mpr (hvsteps i))
    simpa only [D] using hW.mean_tube_renewal_of_pairwise_overlap
      S hmu v C hC hdelayed (hpair v hv0)
  apply hmu.meanBrownianTubeProfile_tendsto_of_exp_defect S hdim hna hm
    hc hD hgamma hbounds
  · intro v hvsteps
    exact (hrenewal v hvsteps).2.1
  · intro v hvsteps
    exact (hrenewal v hvsteps).2.2

end

end BrownianImages
